version: '3.7'

services:
  grafana:
    image: grafana/grafana:9.1.5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./volume/grafana/etc/grafana/provisioning:/etc/grafana/provisioning
      - ./volume/grafana/var/lib/grafana/dashboards/grafana-dashboard.json:/var/lib/grafana/dashboards/grafana-dashboard.json

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
    privileged: true 
    volumes:
      - ./volume/loki/etc/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./volume/loki/loki-data:/mnt/config

  # 1. LOGGER -----------------------------------------------------
  promtail-1:
    image: grafana/promtail:2.5.0
    volumes:
      - ./volume/promtail/1/etc/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./volume/promtail/1/log/:/var/log/dummy/
    command: -config.file=/etc/promtail/promtail-config.yaml

  dummy-logger-1:
    image: busybox
    volumes:
      - ./volume/promtail/1/log/:/var/log/dummy/
    entrypoint: /bin/sh -c "while true; do echo 'dummy log --1-- entry' >> /var/log/dummy/dummy.log; sleep 5; done"

  # 2. LOGGER -----------------------------------------------------
  promtail-2:
    image: grafana/promtail:2.5.0
    volumes:
      - ./volume/promtail/2/etc/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./volume/promtail/2/log/:/var/log/dummy/
    command: -config.file=/etc/promtail/promtail-config.yaml

  dummy-logger-2:
    image: busybox
    volumes:
      - ./volume/promtail/2/log/:/var/log/dummy/
    entrypoint: /bin/sh -c "while true; do echo 'dummy log --2-- entry' >> /var/log/dummy/dummy.log; sleep 5; done"
