version: '3.7'

services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
    privileged: true 
    # links:
      # - prometheus-master
      # - prometheus-slave
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/mnt/config

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log/dummy/:/var/log/dummy/
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:9.1.5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana-dashboard.json:/var/lib/grafana/dashboards/grafana-dashboard.json
    # entrypoint: [ "/bin/bash", "-c", "grafana-server --homepath=/usr/share/grafana & sleep 10 && curl -X POST -H 'Content-Type: application/json' -d @/var/lib/grafana/dashboards/grafana-dashboard.json http://admin:admin@localhost:3000/api/dashboards/db && wait" ]

  dummy-logger:
    image: busybox
    volumes:
      - /var/log/dummy/:/var/log/dummy/
    entrypoint: /bin/sh -c "while true; do echo 'dummy log entry' >> /var/log/dummy/dummy.log; sleep 5; done"

volumes:
  loki-data:
