server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: dummy-logs-1
    static_configs:
      - targets:
          - localhost
        labels:
          job: dummy-logger-1 # Bu satır hizmetin adını belirtir
          __path__: /var/log/dummy/*.log
    pipeline_stages:
      - match:
          selector: '{job="dummy-logger-1"}'
          stages:
            - labels:
                app: dummy-logger-1
